fixup! snapshot: 46.3 → 47.alpha
This reverts commit 3bad12e26fe4d8c5e030d57b1c19e4e2fd5433a7.

TBD later.

error: failed to calculate checksum of: /build/snapshot-47.alpha/vendor/gettext-sys/gettext-0.21.tar.xz

Caused by:
  failed to open file `/build/snapshot-47.alpha/vendor/gettext-sys/gettext-0.21.tar.xz`

Caused by:
  No such file or directory (os error 2)
[51/52] Merging translations for data/org.gnome.Snapshot.metainfo.xml
FAILED: src/snapshot
/nix/store/cnknp3yxfibxjhila0sjd1v3yglqssng-coreutils-9.5/bin/env CARGO_HOME=/build/snapshot-47.alpha/build/cargo-home /nix/store/j6vpbh78ngj2x7jrg27pqjn2cd5mzywl-cargo-1.79.0/bin/cargo build --manifest-path /build/snapshot-47.alpha/Cargo.toml --target-dir /build/snapshot-47.alpha/build/src --release && cp src/release/snapshot src/snapshot
ninja: build stopped: subcommand failed.